version: '3.8'

services:
  db:
    container_name: restaurantDB
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant
    networks:
      - net
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    networks:
      - net
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./postgres/pgadmin:/var/lib/pgadmin
    depends_on:
      - db

  backend:
    container_name: backend
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    networks:
      - net
    depends_on:
      - db
      - pgadmin
    environment:
      - DB_NAME=restaurant
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #   networks:
  #     - net
  #   ports:
  #     - 5173:5173
  #   depends_on:
  #     - db
  #     - pgadmin
  #     - backend
  #   environment:
  #       - VITE_API_URL=http://backend:8000/api

networks:
  net:

volumes:
  postgres_data: